name: Pull Request Review Workflow

on:
  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed

jobs:
  review-job:
    runs-on: ubuntu-latest

    steps:
      - name: Review Action
        run: echo "Review Action = ${{ github.event.action }}"

      - name: Review State
        run: echo "Review State = ${{ github.event.review.state }}"

      - name: PR Title
        run: echo "Pull Request = ${{ github.event.pull_request.title }}"

      - name: Reviewer
        run: echo "Reviewer = ${{ github.actor }}"

      - name: Review Comment
        run: echo "Comment = ${{ github.event.review.body }}"

      - name: Success
        run: echo "Pull Request Review Trigger Executed Successfully!"

