name: Issue Comment Workflow

on:
  issue_comment:
    types:
      - created
      - edited
      - deleted

jobs:
  comment-job:
    runs-on: ubuntu-latest

    steps:
      - name: Display Event
        run: echo "Comment Event = ${{ github.event.action }}"

      - name: Display Comment
        run: echo "Comment = ${{ github.event.comment.body }}"

      - name: Display Issue Title
        run: echo "Issue = ${{ github.event.issue.title }}"

      - name: Display User
        run: echo "Commented By = ${{ github.actor }}"

      - name: Success
        run: echo "Issue Comment Trigger Executed Successfully!"