name: Release Workflow

on:
  release:
    types:
      - published
      - edited

jobs:
  release-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Event
        run: echo "Action = ${{ github.event.action }}"

      - name: Show Release Name
        run: echo "Release Name = ${{ github.event.release.name }}"

      - name: Show Tag
        run: echo "Tag = ${{ github.event.release.tag_name }}"

      - name: Show Repository
        run: echo "Repository = ${{ github.repository }}"

      - name: Show User
        run: echo "Triggered By = ${{ github.actor }}"

      - name: Success
        run: echo "Release Trigger Executed Successfully!"